SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
SENDGRID_USERNAME: alacaza
SENDGRID_PASSWORD: wearealacaza1
MIXPANEL_TOKEN_DEV: d48e6c6f8506472e0b980afbb3494978
MIXPANEL_TOKEN_PROD: 101856fe55346c519aac5f3565dd50cc
