REDISTOGO_URL: redis://localhost:6379/0
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
CLOUDINARY_URL: cloudinary://677747953547754:TrEZJjNmrGH017UH8S2NrZqCVUo@dyp0skivf
MIXPANEL_TOKEN_DEV: d48e6c6f8506472e0b980afbb3494978
PIERRE: pierre@gmail.com
ANABEL: anabel@gmail.com
